import { IS_APPLOCK_ENABLED, IS_BIOMETRIC_ENABLED } from './constants';

export const AsyncStorageKeys = {
	LOGIN_STATUS: 'LOGIN_STATUS',
	USER_LOGIN_DATA: 'USER_LOGIN_DATA',
	DARK_THEME: 'DARK_THEME',
	APP_LOCK: IS_APPLOCK_ENABLED.ENABLED,
	IS_BIOMETRIC_ENABLED: IS_BIOMETRIC_ENABLED.ENABLED,
};
